[package]
name = "http-client"
version = "0.0.1"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 's'

[dependencies]
wit-bindgen = { version = "0.17.0", default-features = false, features = ["realloc"] }

fs = "0.0.5"
rand = "0.8.5"
reqwest = { git = "https://github.com/zivergetech/reqwest", branch = "update-apr-2024", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time = { version = "0.3.21", features = ["formatting"] }

[package.metadata.component.target]
path = "wit"

[package.metadata.component.target.dependencies]
"golem:api" = { path = "wit/deps/golem" }
"golem:rpc" = { path = "wit/deps/wasm-rpc" }
"wasi:clocks" = { path = "wit/deps/clocks" }
"wasi:io" = { path = "wit/deps/io" }
